

Sat Jun 15 02:51:20 2019
random seed 1 - 64466689
random seed 2 - 66601812
random seed 3 - 53760391
bass - John Taylor
keyboards - Nick Rhodes
vocal - Simon Le Bon

Sat Jun 15 02:51:22 2019
random seed 1 - 76827220
random seed 2 - 10905867
random seed 3 - 53860000
bass - John Taylor
keyboards - Nick Rhodes
vocal - Simon Le Bon

Sat Jun 15 02:51:28 2019
random seed 1 - 64466689
random seed 2 - 66601812
random seed 3 - 53760391
bass - John Taylor
keyboards - Nick Rhodes
vocal - Simon Le Bon